platform :ios, '8.0'

target 'HabbityTabbity' do
  use_frameworks!
  pod 'BRYXBanner'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  # Pods for HabbityTabbity

  target 'HabbityTabbityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabbityTabbityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
